spring:
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true
        type: TRACE

    defer-datasource-initialization: true
#  sql:
#    init:
#      mode: never

  security:
    oauth2:
      client:
        registration:
          google:
            클라이언트 아이디: 필요
            클라이언트 비밀키: 필요
            scope:
              - email
              - profile

  datasource:
    url: jdbc:h2:mem:testdb
    username: sa

  h2:
    console:
      enabled: true

jwt:
  issuer: meteorproject529@gmail.com
  secret_key: spring-blog