spring:
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true
        type: TRACE

    defer-datasource-initialization: true
  sql:
    init:
      mode: never

  datasource:
    url: jdbc:h2:mem:testdb

  h2:
    console:
      enabled: true